Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCTask.Models
{
    public class Person
    {
        [RegularExpression("[a-zA-Z]{0,30}")]
        public string Nickname { get; set; }

        [EmailAddress]
        public string Email { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTask.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using MVCTask.Helpers;

namespace MVCTask.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Change(string language)
        {
            if (language == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Empty language");

            var culture = Language.TryCreateCulture(language);
            if (culture == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid language");

            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;

            // Update user language
            HttpCookie cookie = new HttpCookie(Language.Key)
            {
                Value = language
            };

            Response.Cookies.Add(cookie);
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTask.Models;

namespace MVCTask.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCTask.Models;

namespace MVCTask.Controllers
{
    public class PersonController : Controller
    {
        // GET: Person
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Person model)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Model invalid");
            }

            return View(model);
        }
    }
}

Views/Home/Index.cshtml
<div class="jumbotron">
    <p>@Resources.Home.Greeting!</p>
</div>

Views/Login/Index.cshtml
@model MVCTask.Models.Person


<h2>@Resources.Home.Login</h2>


@using (Html.BeginForm("Index", "Person", FormMethod.Post))
{
<div class="form-group">
    <label for="nickInput">@Resources.Login.Nickname</label>
    @Html.TextBoxFor(m => m.Nickname)
</div>
    <div class="form-group">
        <label for="emailInput">@Resources.Login.Email</label>
        @Html.TextBoxFor(m => m.Email)
    </div>
    <button type="submit">@Resources.Login.Submit</button>
}

Views/Person/Index.cshtml
@model MVCTask.Models.Person



<h3>@Model.Nickname</h3>
<h3>@Model.Email</h3>

Views/Shared/_Layout.cshtml
@using MVCTask.Helpers;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVCTask", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Home.Name, "Index", "Home")</li>
                    <li>@Html.ActionLink(Resources.Home.Login, "Index", "Login")</li>
                    <li>
                        <div style="color:white; font-size:1em; margin-top:12px" class="mt-3">
                            <label for="ChangeLanguage">

                                EN-GB
                                @Html.CheckBox("ChangeLanguage", HttpContext.Current.Request.Cookies[Language.Key]?.Value == Language.enGB)
                            </label>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MVCTask</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
    $('#ChangeLanguage').on('change', function () {
        const lang = $('#ChangeLanguage').is(":checked") ? '@(Language.enGB)' : '@(Language.plPL)';
        location.href = '@Url.Action("Change", "Language")?language=' + lang;
    });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>